
SELECT 'PROJECT ' || ID   AS NAME,
DATEDIFF( MONTH, START_DATE, FINISH_DATE ) as MONTH_COUNT
 from PROJECT
WHERE DATEDIFF( MONTH, START_DATE, FINISH_DATE )=
(SELECT DATEDIFF( MONTH, START_DATE, FINISH_DATE )
 from PROJECT 
ORDER BY DATEDIFF( MONTH, START_DATE, FINISH_DATE ) DESC
LIMIT 1);


