SELECT  'PROJECT ' ||pw.PROJECT_ID , SUM (w.SALARY )*datediff(MONTH, START_DATE, FINISH_DATE ) AS PRICE
FROM
PROJECT_WORKER  pw
JOIN WORKER  w ON  pw.WORKER_ID  =w.ID 
JOIN PROJECT p ON pw.PROJECT_ID =p.ID 
GROUP BY  (pw.PROJECT_ID )
ORDER BY(PRICE) DESC;